# Generated by Django 3.2.4 on 2021-07-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
